Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > usb/gadget/f_hid.c:576:2: error: 'hidg_hs_out_ep_desc' undeclared
>  > (first use in this function)
> 
> You're doing something wrong. This chain compiles fine.

Apparently because "# CONFIG_USB_G_HID is not set" in your case.

Patch-set: 1